"use client";
import LightRays from "@/components/LightRays";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsOfService() {
  return (
    <div className="relative min-h-screen text-white font-sans overflow-hidden">
      {/* Background */}
      <div className="fixed inset-0 -z-10 overflow-hidden">
        <LightRays
          raysOrigin="top-center"
          raysColor="#8edaff"
          raysSpeed={1.5}
          lightSpread={2}
          rayLength={2}
          followMouse={true}
          mouseInfluence={0.09}
          noiseAmount={1}
          distortion={0.05}
        />
        <div
          className="absolute inset-0 pointer-events-none"
          style={{
            background:
              "radial-gradient(ellipse at top, #8edaff33 0%, #59c3ff11 70%, transparent 100%)",
            zIndex: 1,
          }}
        />
      </div>

      {/* Navbar */}
      <Navbar />

      {/* Content */}
      <main className="pt-28 sm:pt-32 px-7 sm:px-6 lg:px-12 max-w-4xl mx-auto pb-10 sm:pb-16">
        <h1 className="text-4xl font-bold text-[#8edaff] mb-6">Terms of Service</h1>
        <p className="text-[#eafaff]/80 mb-6">Last updated: {new Date().toLocaleDateString()}</p>

        <p className="mb-4">
          By using <strong>Enqur</strong>, you agree to the following terms and conditions. Please
          read them carefully.
        </p>

        <h2 className="text-2xl font-semibold text-[#8edaff] mt-8 mb-3">User Responsibilities</h2>
        <ul className="list-disc ml-6 text-[#eafaff]/80 space-y-1">
          <li>You agree not to use QR codes for illegal or harmful activities.</li>
          <li>You are responsible for the content linked in your QR codes.</li>
          <li>You must comply with all applicable laws.</li>
        </ul>

        <h2 className="text-2xl font-semibold text-[#8edaff] mt-8 mb-3">Limitation of Liability</h2>
        <p className="text-[#eafaff]/80 mb-4">
          Enqur is not liable for any damages or misuse of QR codes generated by users. Our service is
          provided "as is" without warranties.
        </p>

        <h2 className="text-2xl font-semibold text-[#8edaff] mt-8 mb-3">Changes to Terms</h2>
        <p className="text-[#eafaff]/80">
          We may update these terms from time to time. Continued use of our service constitutes
          acceptance of the updated terms.
        </p>
      </main>

      {/* Footer */}
      <Footer />
    </div>
  );
}
